schema = 3

[mod]
  [mod."github.com/aws/aws-sdk-go"]
    version = "v1.37.29"
    hash = "sha256-CM+2ntRhDMCEUFhfmLEXGBgjGS62AgfJDXfe0CUVRxU="
  [mod."github.com/cpuguy83/go-md2man/v2"]
    version = "v2.0.0-20190314233015-f79a8a8ca69d"
    hash = "sha256-Pi84FPmTnz+Oq8tV9Lx7cMopiMculHkUtUmtWCuaX1s="
  [mod."github.com/davecgh/go-spew"]
    version = "v1.1.1"
    hash = "sha256-nhzSUrE1fCkN0+RL04N4h8jWmRFPPPWbCuDc7Ss0akI="
  [mod."github.com/disintegration/imaging"]
    version = "v1.6.2"
    hash = "sha256-pSeMTPvSkxlthh65LjNYYhPLvCZDkBgVgAGYWW0Aguo="
  [mod."github.com/jmespath/go-jmespath"]
    version = "v0.4.0"
    hash = "sha256-xpT9g2qIXmPq7eeHUXHiDqJeQoHCudh44G/KCSFbcuo="
  [mod."github.com/kr/pretty"]
    version = "v0.1.0"
    hash = "sha256-Fx+TaNrxW0VfzonT2jnd5MU09RRz7GJZkqAtJR6/pKI="
  [mod."github.com/russross/blackfriday/v2"]
    version = "v2.0.1"
    hash = "sha256-smS2RGP+eOAlWkCJKSQZv7PIKUyJIKM/ty+T1nQ8n1o="
  [mod."github.com/shurcooL/sanitized_anchor_name"]
    version = "v1.0.0"
    hash = "sha256-DtFSzeLmD1fAl103ncgwab7Vv2F0aulsA+gbkq24ab8="
  [mod."github.com/sigmonsays/go-logging"]
    version = "v0.0.0-20170415192813-93f4813d2694"
    hash = "sha256-CsxSAqDZ8gaAmdsTRp9C2U2f8PKrIBNdOt8sfAAfA6M="
  [mod."github.com/urfave/cli/v2"]
    version = "v2.3.0"
    hash = "sha256-2QBgrNifcLYb0Ob8WjgBhy5P1rxj1BCYDS9el0ui7jA="
  [mod."golang.org/x/image"]
    version = "v0.0.0-20191009234506-e7c1f5e7dbb8"
    hash = "sha256-rnqWpj/Tj8hw1KfiNjHMQCz+v2AQyOVfCxyzqE5C9zM="
  [mod."golang.org/x/net"]
    version = "v0.0.0-20210226172049-e18ecbb05110"
    hash = "sha256-4u7XpPV+Ersntau6zUiLuNsZQZCIIZs3RouHYl/I02o="
  [mod."golang.org/x/text"]
    version = "v0.3.5"
    hash = "sha256-wObZsr3SvLWITdBBxb5tFdpWCR5OF+RRN6DJl6WQpzE="
  [mod."gopkg.in/check.v1"]
    version = "v1.0.0-20180628173108-788fd7840127"
    hash = "sha256-KsRJNTprd1UijnJusbHwQGM7Bdm45Jt/QL+cIUGNa2w="
  [mod."gopkg.in/yaml.v2"]
    version = "v2.2.8"
    hash = "sha256-/KoaoUbFCm3r8nZyPaWZshMVTM2iSebS5kz/5rc+zsY="
